SUPABASE_URL = "https://dwilfapbpsgdenmpdtht.supabase.co"
SUPABASE_KEY = "sb_publishable_0l6c8RHNOF5n7h65Q0RSsg_yBeP16uy"

# Credentials for WebDAV file storage such as SwitchDrive
[webdav]
base_url = "https://drive.switch.ch/remote.php/webdav/"
username = "miriamfenollosa24@gmail.com"
password = "IUVAQ-CQSOT-YRLNO-PGQVE"